server:
  port: 8820

spring:
  application:
    name: dubbo-study-consumer

dubbo:
  application:
    id: dubbo-study-consumer
    name: dubbo-study-consumer
    owner:
  protocol:
    id: dubbo
    name: dubbo
  consumer:
    group: quick
    version: 1.0.0
    timeout: 3000
  registry:
    id: zookeeper
    protocol: zookeeper
    address: 192.168.20.160:2181
    group: dubbo
    version: 1.0.0
    client: curator